/* eslint-disable react-refresh/only-export-components */
import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import toast, { Toaster } from 'react-hot-toast'
import './styles.css'

const initialInvoices = [
  { id: 'INV-1048', customer: 'Aarav Mehta', date: '02 Sep 2026', amount: 18450, status: 'Paid', initials: 'AM', color: 'lavender' },
  { id: 'INV-1047', customer: 'Priya Shah', date: '01 Sep 2026', amount: 7290, status: 'Pending', initials: 'PS', color: 'peach' },
  { id: 'INV-1046', customer: 'Rohan Verma', date: '30 Aug 2026', amount: 12400, status: 'Paid', initials: 'RV', color: 'mint' },
  { id: 'INV-1045', customer: 'Neha Kapoor', date: '29 Aug 2026', amount: 3960, status: 'Overdue', initials: 'NK', color: 'rose' },
]

const money = (value) => `₹${value.toLocaleString('en-IN')}`

function Icon({ name, size = 19 }) {
  const paths = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    invoice: <><path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6M9 12h6M9 16h3"/></>,
    users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
    chart: <><path d="M3 3v18h18"/><path d="m7 16 4-5 3 3 6-8"/></>,
    settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-1.41 1.41-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21h-2v-.09a1.7 1.7 0 0 0-1.03-1.56 1.7 1.7 0 0 0-1.88.34l-.06.06-1.41-1.41.06-.06A1.7 1.7 0 0 0 9.4 15a1.7 1.7 0 0 0-1.56-1.03H7v-2h.84A1.7 1.7 0 0 0 9.4 11a1.7 1.7 0 0 0-.34-1.88L9 9.06l1.41-1.41.06.06a1.7 1.7 0 0 0 1.88.34A1.7 1.7 0 0 0 13.38 6.5V6h2v.5A1.7 1.7 0 0 0 16.4 8a1.7 1.7 0 0 0 1.88-.34l.06-.06 1.41 1.41-.06.06A1.7 1.7 0 0 0 19.4 11a1.7 1.7 0 0 0 1.56 1.03H21v2h-.04A1.7 1.7 0 0 0 19.4 15Z"/></>,
    plus: <><path d="M12 5v14M5 12h14"/></>, search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>, arrow: <><path d="M5 12h14M13 6l6 6-6 6"/></>, download: <><path d="M12 3v12M7 10l5 5 5-5M5 21h14"/></>, more: <><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>, check: <><path d="m5 12 4 4L19 6"/></>, close: <><path d="m6 6 12 12M18 6 6 18"/></>, arrowUp: <><path d="m18 15-6-6-6 6"/></>, arrowDown: <><path d="m6 9 6 6 6-6"/></>,
  }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>
}

function Layout({ children, onAddInvoice }) {
  const location = useLocation()
  const title = location.pathname === '/invoices' ? 'Invoices' : location.pathname === '/customers' ? 'Customers' : location.pathname === '/reports' ? 'Reports' : location.pathname === '/settings' ? 'Settings' : 'Overview'
  const nav = [
    { path: '/', label: 'Overview', icon: 'grid' }, { path: '/invoices', label: 'Invoices', icon: 'invoice' }, { path: '/customers', label: 'Customers', icon: 'users' }, { path: '/reports', label: 'Reports', icon: 'chart' },
  ]
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">B</div><span>Bill<span>Flow</span></span></div>
      <div className="workspace-label">WORKSPACE</div>
      <nav className="main-nav">{nav.map(item => <NavLink end={item.path === '/'} key={item.path} to={item.path} className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'}><Icon name={item.icon}/><span>{item.label}</span></NavLink>)}</nav>
      <div className="workspace-label second">MANAGE</div>
      <NavLink to="/settings" className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'}><Icon name="settings"/><span>Settings</span></NavLink>
      <div className="sidebar-bottom"><div className="upgrade-card"><div className="upgrade-spark">✦</div><strong>Grow with BillFlow</strong><p>Unlock powerful tools for your shop.</p><button onClick={() => toast('You are already on the best free plan.')}>Explore features <Icon name="arrow" size={14}/></button></div><div className="user-mini"><div className="avatar purple">RK</div><div><strong>Rajesh Kumar</strong><small>Admin account</small></div><Icon name="more" size={18}/></div></div>
    </aside>
    <section className="main-area">
      <header className="topbar"><div><div className="breadcrumb">Workspace <span>/</span> {title}</div><h1>{title}</h1></div><div className="top-actions"><button className="icon-button" aria-label="Search"><Icon name="search"/></button><button className="icon-button notification" aria-label="Notifications"><Icon name="bell"/><i/></button><div className="top-avatar">RK</div></div></header>
      <main className="content">{children}</main>
    </section>
    <button className="floating-add" onClick={onAddInvoice}><Icon name="plus"/> <span>New invoice</span></button>
  </div>
}

function StatCard({ icon, label, value, change, tone, sub }) { return <article className="stat-card"><div className={`stat-icon ${tone}`}><Icon name={icon}/></div><div className="stat-copy"><span>{label}</span><strong>{value}</strong><small className={change?.startsWith('-') ? 'negative' : ''}>{change && <><Icon name={change.startsWith('-') ? 'arrowDown' : 'arrowUp'} size={13}/> {change} <em>vs last month</em></>}{sub}</small></div></article> }

function Overview({ invoices, onAddInvoice }) {
  return <><section className="welcome-row"><div><p className="eyebrow">Tuesday, 2 September 2026</p><h2>Good morning, Rajesh <span>•</span></h2><p className="muted">Here’s what’s happening with your shop today.</p></div><button className="primary-btn" onClick={onAddInvoice}><Icon name="plus" size={17}/> Create invoice</button></section>
    <section className="stats-grid"><StatCard icon="chart" label="Total revenue" value="₹2,48,560" change="12.8%" tone="blue"/><StatCard icon="invoice" label="Total invoices" value="184" change="8.4%" tone="purple"/><StatCard icon="users" label="Active customers" value="96" change="5.2%" tone="peach"/><StatCard icon="bell" label="Pending payments" value="₹32,840" change="-3.1%" tone="mint"/></section>
    <section className="dashboard-grid"><article className="panel revenue-panel"><div className="panel-heading"><div><h3>Revenue overview</h3><p className="muted">Monthly earnings from your invoices</p></div><select defaultValue="6 months"><option>6 months</option><option>This year</option></select></div><div className="chart-wrap"><div className="y-labels"><span>₹60k</span><span>₹40k</span><span>₹20k</span><span>₹0</span></div><div className="chart"><div className="grid-lines"><i/><i/><i/><i/></div><svg viewBox="0 0 600 220" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#7569e8" stopOpacity=".22"/><stop offset="1" stopColor="#7569e8" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 174 C35 167 50 155 83 159 S137 128 166 143 S215 112 250 130 S306 102 333 113 S377 57 417 92 S467 70 500 77 S552 35 600 50 V220 H0Z"/><path className="line" d="M0 174 C35 167 50 155 83 159 S137 128 166 143 S215 112 250 130 S306 102 333 113 S377 57 417 92 S467 70 500 77 S552 35 600 50"/></svg><div className="x-labels"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></div></div></article><article className="panel quick-panel"><div className="panel-heading"><div><h3>Quick actions</h3><p className="muted">Get things done faster</p></div></div><div className="quick-list"><button onClick={onAddInvoice}><span className="quick-icon lavender"><Icon name="invoice"/></span><span><strong>New invoice</strong><small>Create a GST invoice</small></span><Icon name="arrow" size={17}/></button><button onClick={() => toast.success('Customer form is ready!')}><span className="quick-icon peach"><Icon name="users"/></span><span><strong>Add customer</strong><small>Save a new customer</small></span><Icon name="arrow" size={17}/></button><button onClick={() => toast('Reports are updated in real time.')}><span className="quick-icon mint"><Icon name="download"/></span><span><strong>Download report</strong><small>Export your monthly report</small></span><Icon name="arrow" size={17}/></button></div></article></section>
    <section className="panel recent-panel"><div className="panel-heading"><div><h3>Recent invoices</h3><p className="muted">Your latest billing activity</p></div><NavLink to="/invoices" className="view-all">View all <Icon name="arrow" size={15}/></NavLink></div><InvoiceTable invoices={invoices.slice(0, 4)}/></section></>
}

function InvoiceTable({ invoices }) { return <div className="table-scroll"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Date</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{invoices.map(item => <tr key={item.id}><td><strong className="invoice-id">{item.id}</strong></td><td><div className="customer-cell"><span className={`avatar ${item.color}`}>{item.initials}</span>{item.customer}</div></td><td className="muted">{item.date}</td><td><strong>{money(item.amount)}</strong></td><td><span className={`status ${item.status.toLowerCase()}`}><i/>{item.status}</span></td><td><button className="more-btn" onClick={() => toast(`Actions for ${item.id}`)}><Icon name="more"/></button></td></tr>)}</tbody></table></div> }

function Invoices({ invoices, onAddInvoice }) { const [query, setQuery] = useState(''); const filtered = invoices.filter(x => `${x.id} ${x.customer}`.toLowerCase().includes(query.toLowerCase())); return <><section className="page-intro"><div><p className="muted">Manage, track, and share all your customer invoices.</p></div><button className="primary-btn" onClick={onAddInvoice}><Icon name="plus" size={17}/> Create invoice</button></section><section className="panel invoice-page-panel"><div className="toolbar"><div className="search-box"><Icon name="search" size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search invoices or customers..."/></div><select defaultValue="all"><option value="all">All statuses</option><option>Paid</option><option>Pending</option><option>Overdue</option></select></div><InvoiceTable invoices={filtered}/></section></> }
function Customers() { return <><section className="page-intro"><p className="muted">Keep your customer records organized and up to date.</p><button className="primary-btn" onClick={() => toast.success('Customer added successfully')}><Icon name="plus" size={17}/> Add customer</button></section><section className="panel empty-friendly"><div className="big-soft-icon peach"><Icon name="users" size={30}/></div><h3>Your customer list is ready</h3><p className="muted">Add customers to keep track of billing history and pending payments.</p><button className="secondary-btn" onClick={() => toast.success('Customer added successfully')}>Add your first customer</button></section></> }
function Reports() { return <><section className="page-intro"><p className="muted">Understand your shop performance at a glance.</p><button className="secondary-btn" onClick={() => toast.success('Report downloaded')}><Icon name="download" size={16}/> Download report</button></section><section className="stats-grid"><StatCard icon="chart" label="Gross sales" value="₹2,84,920" change="14.2%" tone="blue"/><StatCard icon="invoice" label="Invoices issued" value="184" change="8.4%" tone="purple"/><StatCard icon="check" label="Collection rate" value="88.5%" change="4.6%" tone="mint"/></section><section className="panel empty-friendly report-card"><h3>Your monthly report</h3><p className="muted">Charts and tax summaries will appear here as your shop grows.</p></section></> }
function Settings() { return <section className="settings-layout"><div className="settings-nav panel"><strong>Settings</strong><button className="selected">Business profile</button><button>Invoice preferences</button><button>Tax & GST</button><button>Notifications</button></div><div className="panel settings-form"><div className="panel-heading"><div><h3>Business profile</h3><p className="muted">This information appears on your invoices.</p></div></div><div className="form-grid"><label>Business name<input defaultValue="Rajesh General Store"/></label><label>GSTIN<input defaultValue="27AABCU9603R1ZM"/></label><label>Phone number<input defaultValue="+91 98765 43210"/></label><label>Email address<input defaultValue="hello@rajeshstore.in"/></label><label className="wide">Business address<textarea defaultValue="12 Market Road, Pune, Maharashtra 411001"/></label></div><button className="primary-btn" onClick={() => toast.success('Settings saved')}>Save changes</button></div></section> }

function App() { const [invoices, setInvoices] = useState(initialInvoices); const [modal, setModal] = useState(false); const addInvoice = (e) => { e.preventDefault(); const form = new FormData(e.currentTarget); const customer = form.get('customer') || 'New customer'; const amount = Number(form.get('amount')) || 0; setInvoices(prev => [{ id: `INV-${1050 + prev.length}`, customer, date: '02 Sep 2026', amount, status: 'Pending', initials: customer.split(' ').map(x => x[0]).join('').slice(0, 2).toUpperCase(), color: 'lavender' }, ...prev]); setModal(false); toast.success('Invoice created successfully'); }; return <BrowserRouter><Layout onAddInvoice={() => setModal(true)}><Routes><Route path="/" element={<Overview invoices={invoices} onAddInvoice={() => setModal(true)}/>}/><Route path="/invoices" element={<Invoices invoices={invoices} onAddInvoice={() => setModal(true)}/>}/><Route path="/customers" element={<Customers/>}/><Route path="/reports" element={<Reports/>}/><Route path="/settings" element={<Settings/>}/></Routes></Layout><Toaster position="bottom-right" toastOptions={{ style: { borderRadius: '12px', fontFamily: 'Inter, sans-serif' } }}/>{modal && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setModal(false)}><form className="modal" onSubmit={addInvoice}><div className="modal-head"><div><h3>Create invoice</h3><p className="muted">Add a quick invoice for your customer.</p></div><button type="button" className="close-btn" onClick={() => setModal(false)}><Icon name="close"/></button></div><label>Customer name<input name="customer" required placeholder="e.g. Amit Sharma" autoFocus/></label><label>Invoice amount<input name="amount" required type="number" min="1" placeholder="e.g. 2500"/></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={() => setModal(false)}>Cancel</button><button className="primary-btn" type="submit">Create invoice</button></div></form></div>}</BrowserRouter> }

createRoot(document.getElementById('root')).render(<App />)
