/* eslint-disable react-refresh/only-export-components */
import { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, NavLink, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { createClient } from '@supabase/supabase-js'
import toast, { Toaster } from 'react-hot-toast'
import './styles.css'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY
const supabaseConfigured = Boolean(supabaseUrl && supabaseAnonKey)
const supabase = supabaseConfigured ? createClient(supabaseUrl, supabaseAnonKey) : null

const products = [
  { sku: 'RICE-5KG', barcode: '8901234567890', name: 'Premium Rice 5kg', price: 460, tax: 5 },
  { sku: 'OIL-1L', barcode: '8901234567891', name: 'Sunflower Oil 1L', price: 165, tax: 5 },
  { sku: 'SOAP-3PK', barcode: '8901234567892', name: 'Bath Soap 3 Pack', price: 120, tax: 18 },
  { sku: 'TEA-250G', barcode: '8901234567893', name: 'Assam Tea 250g', price: 185, tax: 5 },
]
const seedInvoices = [
  { id: 'INV-1048', customer: 'Aarav Mehta', date: '02 Sep 2026', items: [{ ...products[0], quantity: 2 }], status: 'Paid', payment: 'UPI' },
  { id: 'INV-1047', customer: 'Priya Shah', date: '01 Sep 2026', items: [{ ...products[2], quantity: 2 }], status: 'Pending', payment: 'Cash' },
]
const money = value => `₹${Math.round(value).toLocaleString('en-IN')}`
const initials = name => name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase()

function Icon({ name, size = 19 }) {
  const paths = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    invoice: <><path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6M9 12h6M9 16h3"/></>,
    users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
    chart: <><path d="M3 3v18h18"/><path d="m7 16 4-5 3 3 6-8"/></>, settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-1.41 1.41-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21h-2v-.09a1.7 1.7 0 0 0-1.03-1.56 1.7 1.7 0 0 0-1.88.34l-.06.06-1.41-1.41.06-.06A1.7 1.7 0 0 0 9.4 15a1.7 1.7 0 0 0-1.56-1.03H7v-2h.84A1.7 1.7 0 0 0 9.4 11a1.7 1.7 0 0 0-.34-1.88L9 9.06l1.41-1.41.06.06a1.7 1.7 0 0 0 1.88.34A1.7 1.7 0 0 0 13.38 6.5V6h2v.5A1.7 1.7 0 0 0 16.4 8a1.7 1.7 0 0 0 1.88-.34l.06-.06 1.41 1.41-.06.06A1.7 1.7 0 0 0 19.4 11a1.7 1.7 0 0 0 1.56 1.03H21v2h-.04A1.7 1.7 0 0 0 19.4 15Z"/></>, plus: <><path d="M12 5v14M5 12h14"/></>, search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, camera: <><path d="M4 7h3l2-3h6l2 3h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2Z"/><circle cx="12" cy="13" r="3"/></>, close: <><path d="m6 6 12 12M18 6 6 18"/></>, arrow: <><path d="M5 12h14M13 6l6 6-6 6"/></>, check: <path d="m5 12 4 4L19 6"/>, download: <><path d="M12 3v12M7 10l5 5 5-5M5 21h14"/></>, more: <><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>,
  }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>
}

function Auth({ onAuth }) {
  const [mode, setMode] = useState('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState('Owner'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async event => { event.preventDefault(); setError(''); if (!email.includes('@') || password.length < 6) return setError('Enter a valid email and a password of at least 6 characters.'); setBusy(true)
    try { if (supabase) { const result = mode === 'login' ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { data: { role } } }); if (result.error) throw result.error; if (mode === 'login' && !result.data.user) throw new Error('Unable to start your session.'); if (mode === 'signup' && !result.data.session) { setError('Account created. Check your email to confirm, then sign in.'); setMode('login') } else onAuth({ email, name: email.split('@')[0], role: result.data.user?.user_metadata?.role || role }) } else { onAuth({ email, name: email.split('@')[0], role }) } } catch (err) { setError(err.message || 'Authentication failed. Please try again.') } finally { setBusy(false) }
  }
  return <main className="auth-shell"><section className="auth-card"><div className="brand auth-brand"><div className="brand-mark">B</div><span>Bill<span>Flow</span></span></div><h1>{mode === 'login' ? 'Welcome back' : 'Create your workspace'}</h1><p className="muted">{supabaseConfigured ? 'Securely sign in with Supabase Auth.' : 'Preview mode is active. Add Supabase keys for production authentication.'}</p>{!supabaseConfigured && <div className="notice">Supabase is not configured. Demo sessions are kept in this browser only.</div>}<div className="auth-tabs"><button className={mode === 'login' ? 'selected' : ''} onClick={() => { setMode('login'); setError('') }}>Login</button><button className={mode === 'signup' ? 'selected' : ''} onClick={() => { setMode('signup'); setError('') }}>Sign up</button></div><form onSubmit={submit}><label>Email address<input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="you@shop.com" required /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="At least 6 characters" required /></label>{mode === 'signup' && <label>Workspace role<select value={role} onChange={event => setRole(event.target.value)}><option>Owner</option><option>Employee</option><option>Customer</option></select></label>}{error && <p className="form-error">{error}</p>}<button className="primary-btn full" disabled={busy}>{busy ? 'Working…' : mode === 'login' ? 'Login to BillFlow' : 'Create account'}</button></form></section></main>
}

function Layout({ user, onLogout, children }) { const location = useLocation(); const title = location.pathname === '/' ? 'Overview' : location.pathname.slice(1).split('/')[0].replace(/\b\w/g, x => x.toUpperCase()); const links = [{ path: '/', label: 'Overview', icon: 'grid', roles: ['Owner'] }, { path: '/pos', label: 'POS billing', icon: 'invoice', roles: ['Owner', 'Employee'] }, { path: '/invoices', label: 'Invoices', icon: 'invoice', roles: ['Owner', 'Employee', 'Customer'] }, { path: '/customers', label: 'Customers', icon: 'users', roles: ['Owner'] }, { path: '/reports', label: 'Reports', icon: 'chart', roles: ['Owner'] }]; return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">B</div><span>Bill<span>Flow</span></span></div><div className="workspace-label">WORKSPACE</div><nav className="main-nav">{links.filter(link => link.roles.includes(user.role)).map(link => <NavLink end={link.path === '/'} key={link.path} to={link.path} className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'}><Icon name={link.icon}/><span>{link.label}</span></NavLink>)}</nav><div className="workspace-label second">MANAGE</div>{user.role === 'Owner' && <NavLink to="/settings" className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'}><Icon name="settings"/><span>Settings</span></NavLink>}<div className="sidebar-bottom"><div className="user-mini"><div className="avatar purple">{initials(user.name)}</div><div><strong>{user.name}</strong><small>{user.role} account</small></div><button aria-label="Sign out" onClick={onLogout}><Icon name="more" size={18}/></button></div></div></aside><section className="main-area"><header className="topbar"><div><div className="breadcrumb">Workspace <span>/</span> {title}</div><h1>{title}</h1></div><div className="top-actions"><span className="role-badge">{user.role}</span><div className="top-avatar">{initials(user.name)}</div></div></header><main className="content">{children}</main></section></div> }

function Protected({ user, roles, children }) { return roles.includes(user.role) ? children : <Navigate to="/invoices" replace /> }
function ProductSearch({ onAdd }) { const [query, setQuery] = useState(''); const matches = products.filter(item => `${item.name} ${item.sku} ${item.barcode}`.toLowerCase().includes(query.toLowerCase())); return <section className="panel product-search"><div className="search-box"><Icon name="search" size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search product, SKU or barcode…" /></div><div className="product-results">{matches.map(item => <button key={item.sku} onClick={() => onAdd(item)}><span><strong>{item.name}</strong><small>{item.sku} · {item.barcode}</small></span><b>{money(item.price)}</b></button>)}</div></section> }
function Scanner({ onCode }) { const videoRef = useRef(null); const streamRef = useRef(null); const [active, setActive] = useState(false); const [message, setMessage] = useState('Camera is off'); const start = async () => { try { if (!('BarcodeDetector' in window)) return setMessage('Live barcode detection is not supported here. Use manual entry below.'); const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } }); streamRef.current = stream; videoRef.current.srcObject = stream; await videoRef.current.play(); setActive(true); setMessage('Point the camera at a barcode'); const detector = new window.BarcodeDetector(); const scan = async () => { if (!streamRef.current) return; try { const codes = await detector.detect(videoRef.current); if (codes[0]?.rawValue) onCode(codes[0].rawValue) } catch { /* camera frames can be unavailable between reads */ } requestAnimationFrame(scan) }; scan() } catch (err) { setMessage(err.message || 'Camera permission was denied.') } }; const stop = () => { streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; setActive(false); setMessage('Camera is off') }; useEffect(() => () => stop(), []); return <section className="scanner panel"><div className="panel-heading"><div><h3>Barcode scanner</h3><p className="muted">Continuous camera scanning for SKU lookup</p></div><button className="secondary-btn" onClick={active ? stop : start}><Icon name="camera" size={16}/>{active ? 'Stop' : 'Start camera'}</button></div><div className="camera-box">{active ? <video ref={videoRef} muted playsInline /> : <div className="camera-placeholder"><Icon name="camera" size={30}/><span>{message}</span></div>}</div><small className="muted">{message}</small></section> }

function Cart({ cart, setCart, onCheckout }) { const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); const tax = cart.reduce((sum, item) => sum + item.price * item.quantity * item.tax / 100, 0); const total = subtotal + tax; const change = (sku, amount) => setCart(items => items.map(item => item.sku === sku ? { ...item, quantity: Math.max(0, item.quantity + amount) } : item).filter(item => item.quantity)); return <section className="panel cart-panel"><div className="panel-heading"><div><h3>Current cart</h3><p className="muted">{cart.reduce((sum, item) => sum + item.quantity, 0)} items</p></div><button className="text-btn" onClick={() => setCart([])}>Clear</button></div>{cart.length === 0 ? <div className="empty-friendly compact"><Icon name="invoice" size={28}/><p>Scan or search products to begin.</p></div> : <div className="cart-lines">{cart.map(item => <div className="cart-line" key={item.sku}><div><strong>{item.name}</strong><small>{item.sku} · {money(item.price)} + {item.tax}% GST</small></div><div className="quantity"><button onClick={() => change(item.sku, -1)}>−</button><b>{item.quantity}</b><button onClick={() => change(item.sku, 1)}>+</button></div><strong>{money(item.price * item.quantity)}</strong></div>)}</div>}<div className="totals"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>GST</span><b>{money(tax)}</b></div><div className="grand-total"><span>Total</span><strong>{money(total)}</strong></div></div><button className="primary-btn full" disabled={!cart.length} onClick={() => onCheckout({ subtotal, tax, total })}>Create invoice</button></section> }

function POS({ onInvoice }) { const [cart, setCart] = useState([]); const [manual, setManual] = useState(''); const add = product => { setCart(items => items.some(item => item.sku === product.sku) ? items.map(item => item.sku === product.sku ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { ...product, quantity: 1 }]); setManual(''); toast.success(`${product.name} added`) }; const code = value => { const product = products.find(item => item.barcode === value || item.sku.toLowerCase() === value.toLowerCase()); if (product) add(product); else if (value) toast.error('No product matches that barcode or SKU') }; return <><section className="page-intro"><div><p className="muted">Scan products, calculate GST, and issue a digital receipt.</p></div></section><div className="pos-grid"><div><Scanner onCode={code}/><div className="panel manual-entry"><label>Manual barcode / SKU entry<div className="inline-form"><input value={manual} onChange={event => setManual(event.target.value)} onKeyDown={event => event.key === 'Enter' && code(manual)} placeholder="8901234567890 or RICE-5KG"/><button className="primary-btn" onClick={() => code(manual)}>Add item</button></div></label></div><ProductSearch onAdd={add}/></div><Cart cart={cart} setCart={setCart} onCheckout={summary => { onInvoice({ customer: 'Walk-in customer', items: cart, ...summary }); setCart([]) }}/></div></> }

function InvoiceTable({ invoices }) { const navigate = useNavigate(); return <div className="table-scroll"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Date</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{invoices.map(item => <tr key={item.id}><td><strong className="invoice-id">{item.id}</strong></td><td>{item.customer}</td><td className="muted">{item.date}</td><td><strong>{money(item.total || item.items?.reduce((sum, x) => sum + x.price * x.quantity * (1 + x.tax / 100), 0) || 0)}</strong></td><td><span className={`status ${item.status.toLowerCase()}`}><i/>{item.status}</span></td><td><button className="more-btn" onClick={() => navigate(`/invoice/${item.id}`)}><Icon name="arrow" size={16}/></button></td></tr>)}</tbody></table></div> }
function Invoices({ invoices }) { const [query, setQuery] = useState(''); const filtered = invoices.filter(item => `${item.id} ${item.customer}`.toLowerCase().includes(query.toLowerCase())); return <><section className="page-intro"><p className="muted">Shareable digital invoices and customer payment status.</p></section><section className="panel invoice-page-panel"><div className="toolbar"><div className="search-box"><Icon name="search" size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search invoices or customers…"/></div></div><InvoiceTable invoices={filtered}/></section></> }
function InvoiceDetail({ invoices }) { const { id } = useParams(); const invoice = invoices.find(item => item.id === id); if (!invoice) return <section className="panel empty-friendly"><h3>Invoice not found</h3><p className="muted">This link may be expired or the invoice was removed.</p></section>; const subtotal = invoice.subtotal ?? invoice.items.reduce((sum, item) => sum + item.price * item.quantity, 0); const tax = invoice.tax ?? invoice.items.reduce((sum, item) => sum + item.price * item.quantity * item.tax / 100, 0); const total = invoice.total ?? subtotal + tax; return <section className="invoice-detail panel"><div className="receipt-head"><div><p className="eyebrow">DIGITAL INVOICE</p><h2>{invoice.id}</h2><p className="muted">{invoice.date} · BillFlow</p></div><span className={`status ${invoice.status.toLowerCase()}`}><i/>{invoice.status}</span></div><div className="receipt-customer"><span>Billed to</span><strong>{invoice.customer}</strong></div>{invoice.items.map(item => <div className="receipt-item" key={item.sku}><span>{item.name}<small>{item.quantity} × {money(item.price)}</small></span><strong>{money(item.price * item.quantity)}</strong></div>)}<div className="totals"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>GST</span><b>{money(tax)}</b></div><div className="grand-total"><span>Total paid</span><strong>{money(total)}</strong></div></div><div className="share-box"><input readOnly value={`${window.location.origin}/invoice/${invoice.id}`} onFocus={event => event.target.select()}/><button className="secondary-btn" onClick={() => { navigator.clipboard?.writeText(window.location.href); toast.success('Invoice link copied') }}>Copy link</button></div></section> }
function Overview({ invoices }) { return <><section className="welcome-row"><div><p className="eyebrow">Tuesday, 2 September 2026</p><h2>Good morning, BillFlow <span>•</span></h2><p className="muted">Your billing workspace at a glance.</p></div><NavLink className="primary-btn" to="/pos"><Icon name="plus" size={17}/> New bill</NavLink></section><section className="stats-grid"><article className="stat-card"><div className="stat-icon blue"><Icon name="chart"/></div><div className="stat-copy"><span>Total revenue</span><strong>{money(invoices.reduce((sum, item) => sum + (item.total || 0), 248560))}</strong><small>12.8% <em>vs last month</em></small></div></article><article className="stat-card"><div className="stat-icon purple"><Icon name="invoice"/></div><div className="stat-copy"><span>Total invoices</span><strong>{invoices.length + 182}</strong><small>8.4% <em>vs last month</em></small></div></article><article className="stat-card"><div className="stat-icon peach"><Icon name="users"/></div><div className="stat-copy"><span>Active customers</span><strong>96</strong><small>5.2% <em>vs last month</em></small></div></article></section><section className="panel recent-panel"><div className="panel-heading"><div><h3>Recent invoices</h3><p className="muted">Your latest billing activity</p></div><NavLink to="/invoices" className="view-all">View all <Icon name="arrow" size={15}/></NavLink></div><InvoiceTable invoices={invoices.slice(0, 5)}/></section></> }
function SimplePage({ title, text, icon = 'users' }) { return <section className="panel empty-friendly"><div className="big-soft-icon peach"><Icon name={icon} size={30}/></div><h3>{title}</h3><p className="muted">{text}</p></section> }

function App() { const [user, setUser] = useState(null); const [invoices, setInvoices] = useState(() => { try { return JSON.parse(localStorage.getItem('billflow-invoices')) || seedInvoices } catch { return seedInvoices } }); useEffect(() => { localStorage.setItem('billflow-invoices', JSON.stringify(invoices)) }, [invoices]); useEffect(() => { if (supabase) supabase.auth.getSession().then(({ data }) => { if (data.session?.user) setUser({ email: data.session.user.email, name: data.session.user.email?.split('@')[0], role: data.session.user.user_metadata?.role || 'Employee' }) }) }, []); const createInvoice = data => { const invoice = { ...data, id: `INV-${1050 + invoices.length}`, date: new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), status: 'Pending', payment: 'Pending' }; setInvoices(prev => [invoice, ...prev]); toast.success('Invoice created — shareable link ready'); }; return <BrowserRouter>{user ? <Layout user={user} onLogout={async () => { await supabase?.auth.signOut(); setUser(null) }}><Routes><Route path="/" element={<Protected user={user} roles={['Owner']}><Overview invoices={invoices}/></Protected>}/><Route path="/pos" element={<Protected user={user} roles={['Owner', 'Employee']}><POS onInvoice={createInvoice}/></Protected>}/><Route path="/invoices" element={<Invoices invoices={invoices}/>}/><Route path="/invoice/:id" element={<InvoiceDetail invoices={invoices}/>}/><Route path="/customers" element={<Protected user={user} roles={['Owner']}><SimplePage title="Customer management" text="Owner-only customer records and billing history."/></Protected>}/><Route path="/reports" element={<Protected user={user} roles={['Owner']}><SimplePage title="Sales analytics" text="Owner-only revenue, GST, and collection reporting." icon="chart"/></Protected>}/><Route path="/settings" element={<Protected user={user} roles={['Owner']}><SimplePage title="Workspace settings" text="Configure business profile, tax rules, and team permissions." icon="settings"/></Protected>}/><Route path="*" element={<Navigate to="/invoices" replace/>}/></Routes></Layout> : <Routes><Route path="/invoice/:id" element={<InvoiceDetail invoices={invoices}/>}/><Route path="*" element={<Auth onAuth={setUser}/>}/></Routes>}<Toaster position="bottom-right"/></BrowserRouter> }

createRoot(document.getElementById('root')).render(<App />)
